apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: login-app
  namespace: my-ns
  labels:
    app.kubernetes.io/name: login-app
    app.kubernetes.io/env: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: login-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: login-app
    spec:
      containers:
        - name: httpd
          image: httpd


