apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-ns
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/env: development
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/env: development
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
        app.kubernetes.io/env: development
    spec:
      containers:
        - name: nginx
          image: nginx:1.27