apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sales-app
  namespace: my-ns
spec:
  maxReplicas: 12
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sales-app

