---
# tasks file for basic
- block:
  - name: general setting
    include_tasks: general.yml

      #  - name: Copy resolve.conf to remote servers
      #    template:
      #      src: resolv.conf.j2
      #      dest: /etc/resolv.conf
      #
      #  - name: debina setting
      #    include_tasks: debina.yml

  when: ansible_os_family == "Debian"

- block:
    - name: Copy resolve.conf to remote servers
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Copy sample confing file
      template:
        src: sample.conf.j2
        dest: /opt/sample.conf

  when: ansible_os_family == "Debian"
