
version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    ports:
     - '3000:3000'
    volumes:
     - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
