version: '3.8'

services:
  db:
    image: docker.io/library/mariadb:11
    container_name: mariadb-1
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

volumes:
  dbdata:


