---
# tasks file for basic

- name: Install zabbix and Requirment
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.3-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - libpq-dev
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Start Postgres Services
  service:
    name: postgresql
    state: started
    enabled: yes

- name: IP
  shell:
    cmd: hostname -I | awk '{print $2}'
  register: output_file

- name: Zabbix Config
  include_tasks:
    file: zabbix_config.yml

- name: Restart zabbix-server services
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart zabbix-agent services
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: Restart Appache services
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Show IP Address
  debug:
    msg: "The IP Address is: {{ output_file.stdout }}"

